services:

    zookeeper:
        image: bitnami/zookeeper:3.9.0
        restart: always
        environment:
            ALLOW_ANONYMOUS_LOGIN: yes
            ZOO_PORT_NUMBER: 2181
        ports:
            - "2181:2181"

    kafka:
        image: bitnami/kafka:3.9.0
        restart: always
        depends_on:
            - zookeeper
        environment:
            ALLOW_PLAINTEXT_LISTENER: yes
            KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
            KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
            KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        ports:
            - "9092:9092"

    schema-registry:
        image: bitnami/schema-registry:7.8.0
        restart: always
        environment:
            SCHEMA_REGISTRY_KAFKA_BROKERS: PLAINTEXT://kafka:9092
        ports:
            - "8081:8081"

    kafka-ui:
        image: provectuslabs/kafka-ui:v0.7.2
        restart: always
        environment:
            KAFKA_CLUSTERS_0_NAME: local-cluster
            KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS: kafka:9092
            KAFKA_CLUSTERS_0_SCHEMA_REGISTRY: http://schema-registry:8081
        depends_on:
            - kafka
            - schema-registry
        ports:
            - "8080:8080"

    app:
        image: wallanaq/sb-eda-kafka:0.0.1
        environment:
            BOOTSTRAP_SERVERS: kafka:9092
            SCHEMA_REGISTRY_URL: http://schema-registry:8081
        depends_on:
            - kafka
        ports:
            - "9080:8080"

networks:
    default:
        name: appdev
        driver: bridge
