server:
  port: {APP_PORT:80801}
  servlet:
    context-path: /api/v1

spring:
  application:
    name: sb-eda-kafka

  kafka:
    bootstrap-servers: ${BOOTSTRAP_SERVERS:localhost:9092}
    properties:
      schema.registry.url: ${SCHEMA_REGISTRY_URL:http://localhost:8081}
      specific.avro.reader: true
      enable.auto.commit: false
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      acks: ${ACKS:all}
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      group-id: event-consumers
      client-id: ${HOSTNAME:sb-eda-kafka}
      auto-offset-reset: earliest
    listener:
      ack-mode: manual
    retry:
      topics:
        enabled: true
