server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  application:
    name: sb-eda-kafka

  kafka:
    bootstrap-servers: kafka1:9092, kafka2:9093
    properties:
      schema.registry.url: http://schema-registry:8081
      specific.avro.reader: true
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      acks: all